import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header"
import Footer from "@/components/Footer"

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} font-sans antialiased h-full overflow-hidden bg-background text-foreground`}>
          <Header />
          {/* Main content with padding for spacing and adjusted height */}
          <main className="py-4 h-[calc(100vh-11rem)] overflow-hidden">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
